# Generated by Django 5.2.9 on 2026-06-12
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_task_subscribers"),
    ]

    operations = [
        migrations.CreateModel(
            name="RasterFramePreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", s3_file_field.fields.S3FileField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("bounds", models.JSONField()),
                (
                    "layer_frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_previews",
                        to="core.layerframe",
                    ),
                ),
                (
                    "layer_style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frame_previews",
                        to="core.layerstyle",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("layer_style", "layer_frame"),
                        name="unique_layer_style_layer_frame_preview",
                    )
                ],
            },
        ),
    ]
