# Generated by Django 5.2.9 on 2026-06-25
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import s3_file_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_taskresult_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerstyle",
            name="raster_style_params",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="RasterFramePreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "Creating"),
                            ("regenerating", "Regenerating"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="creating",
                        max_length=16,
                    ),
                ),
                (
                    "style_fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("image", s3_file_field.fields.S3FileField(blank=True, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("bounds", models.JSONField(blank=True, default=dict)),
                (
                    "layer_frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_previews",
                        to="core.layerframe",
                    ),
                ),
                (
                    "layer_style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frame_previews",
                        to="core.layerstyle",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("layer_style", "layer_frame"),
                        name="unique_layer_style_layer_frame_preview",
                    )
                ],
            },
        ),
    ]
