# Generated by Django 6.0.7 on 2026-08-10 17:56

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_taskresult_creator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fileitem",
            options={},
        ),
        migrations.AddConstraint(
            model_name="fileitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("chart__isnull", True), ("dataset__isnull", False)),
                    models.Q(("chart__isnull", False), ("dataset__isnull", True)),
                    _connector="OR",
                ),
                name="dataset_or_chart_constraint",
            ),
        ),
    ]
