# Generated by Django 6.0.7 on 2026-08-07 17:26

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_taskresult_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="allow_unauthenticated",
            field=models.BooleanField(default=False),
        ),
    ]
