# Generated by Django 6.0.7 on 2026-08-17 17:21

from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_project_allow_unauthenticated"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="region",
            name="unique-source-region-name",
        ),
        migrations.AddField(
            model_name="region",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="core.project",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="dataset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="core.dataset",
            ),
        ),
        migrations.AddConstraint(
            model_name="region",
            constraint=models.UniqueConstraint(
                fields=("project", "dataset", "name"), name="unique-region-name"
            ),
        ),
        migrations.AddConstraint(
            model_name="region",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("dataset__isnull", False), ("project__isnull", True)),
                    models.Q(("dataset__isnull", True), ("project__isnull", False)),
                    _connector="OR",
                ),
                name="dataset_or_project_constraint",
            ),
        ),
    ]
