# Generated by Django 6.0.7 on 2026-09-11 17:40

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_layerstyle_raster_style_params_rasterframepreview"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ViewState",
            new_name="Bookmark",
        ),
    ]
