# Generated by Django 6.0.7 on 2026-09-18 19:18

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_bookmarks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layer",
            name="default_style",
        ),
        migrations.AddField(
            model_name="layerstyle",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
