# Generated by Django 6.1.1 on 2026-09-30 20:17

from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_proj_scoped_default_styles"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkAnimation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="NetworkComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("index", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="bookmark",
            name="uniqueviewname",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="network_animation_config",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="network_animation_tick",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="current_basemap",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="core.basemap",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="current_chart",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="core.chart",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="current_network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="core.network",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="current_result",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="core.taskresult",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="core.project",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="selected_layers",
            field=models.ManyToManyField(blank=True, related_name="bookmarks", to="core.layer"),
        ),
        migrations.AddField(
            model_name="networkanimation",
            name="network",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animations",
                to="core.network",
            ),
        ),
        migrations.AddField(
            model_name="networkanimation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animations",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="networkanimation",
            name="sync_layers",
            field=models.ManyToManyField(blank=True, to="core.layer"),
        ),
        migrations.AddField(
            model_name="networkanimation",
            name="task_result",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="animations",
                to="core.taskresult",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="current_network_animation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="core.networkanimation",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="uniquebookmarkname"
            ),
        ),
        migrations.AddField(
            model_name="networkcomponent",
            name="nodes",
            field=models.ManyToManyField(blank=True, to="core.networknode"),
        ),
        migrations.AddField(
            model_name="networkstate",
            name="animation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="core.networkanimation",
            ),
        ),
        migrations.AddField(
            model_name="networkstate",
            name="deactivated_nodes",
            field=models.ManyToManyField(blank=True, to="core.networknode"),
        ),
        migrations.AddField(
            model_name="networkcomponent",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="core.networkstate",
            ),
        ),
        migrations.AddConstraint(
            model_name="networkanimation",
            constraint=models.UniqueConstraint(
                fields=("name", "network", "project"), name="unique_name_network_project"
            ),
        ),
    ]
